### ISSUE TITLE
what to do with empty server-configs?

### ISSUE THREAD

**Issue by r10s** [deltachat/provider-db#113]
currently, the format allows an empty `server`-section.

if the empty `server`-section is combined eg. with a `before_login_hint` the provider may stop working.

reason for that is:
- for domains _without_ a provider-db entry, we check for autoconfig.xml, eg. [here for systemli.org](https://www.systemli.org/.well-known/autoconfig/mail/config-v1.1.xml).
- if a domain has a provider-db-entry, however, this step is skipped, for various reasons - performance, reliability, privacy
- if now the provider-db-entry does not contain the same information than the autoconfig.xml before, things stop working

this issue is mitigated as some common servernames are probed, however, in the example, mail.systemli.org would not be used. also the fact, that entries, that are just "OK" are not included to the database at all mitigates the issue.

to solve that, we could:
1. not allow empty server sections at all (just OK could be fine, but whenever a field is written to rust, the sever part is required)
2. check autoconfig.xml implicitly when a server-section is missing

currently, this affects aol, fastmail, protonmail, t-online, yandex

**Comment by xshadow** [comment]
Just a side note:  From an operators point of view, we do not want to store my mail configuration in multiple places, that's why we didn't store systemli.org's mail configuration in the providerdb. The autoconfig.xml gives the provider the freedom  to change it's mail configuration whenever he wants/needs it. Those changes would be automatically rolled out to all future users. 

To have it set/defined in a different place, such as provider-db would mean, whenever we want to change our mail setup, we have to update this information in this repository. Though this is a small tasks, but it tends to be forgotten, which would lead to an non-functional delta chat setup. 

Though, we want to be part of the delta-chat project :) Thank you for your time and work!

**Comment by hpk42** [comment]
I wonder if we could refine the configuration logic to only avoid autoconfig/probing 
if the providerdb actually specifies it. 

@xshadow FYI there are some providers where we fail to auto-configure and the
provider-db settings make it work for users.  Another thing is if you could
provide us with a test account for system.li -- we plan to write some cross-provider
tests and can include all those where we have test accounts.

**Comment by r10s** [comment]
yip, i also think, we shoud go for 2. - this way one cannot break a provider by just adding a before-login-hint saying it needs some preparations.

only if a `server` section is specified, autoconfig would be skipped. this has to bve changed in the core, however.

**Comment by r10s** [comment]
in fact, we always did 2. sorry for the noise.
