### ISSUE TITLE
ProviderDB add strato.de

### ISSUE THREAD

**Issue by w-wagner** [deltachat/provider-db#167]
Strato allows you to create email addresses for your own domain. So the domain does not match the mail server domain.
In the moment deltachat seems to be unable to find the mail servers automatically.

imap.strato.de
smtp.strato.de

is what needs to be added, to make it work.

This small configuration might be an issue for the general audience, as easy as it is. Perfect would be, to add the mail server setup to the autoconfig, just like thunderbird does it, for instance.

Great work. Thank you!

**Comment by keppo070** [comment]
it seems Strato uses several domains


POP3 (inkomende berichten, SSL/TLS) | pop3.strato.com | 995
IMAP (inkomende berichten, SSL/TLS) | imap.strato.com | 993
SMTP-server (uitgaande berichten, SSL/TLS) | smtp.strato.com | 465 / 587

**Comment by missytake** [comment]
This provider supports custom domains, which is not supported yet, but will be tackled soon(tm). Will be reopened then.

**Comment by hoyalu** [comment]
Beware: Even though it looks like everything was working fine, Strato sometimes blocks outgoing messages because of strict filters. Sending a link as the only content of a message sometimes works, sometimes doesn't. This depends on the actual link and on Strato's policy for outgoing spam detection which is not published. Shouldn't be a problem with encrypted chats, but can be a pain without encryption. I wouldn't recommend Strato for Delta Chat.
