### ISSUE TITLE
Add QQ Mail

### ISSUE THREAD

**Issue by digitalethics** [deltachat/provider-db#179]
Could you add [QQ Mail](https://en.mail.qq.com/) to the list at https://providers.delta.chat/ and provide instructions how to set it up? Not that I recommend this provider in any way but it would allow to better keep in touch with Chinese friends via Delta Chat. Many thanks!

**Comment by yhh2021** [comment]
QQ Mail works out of the box. 163 mail doesn't work, see [this link](https://help.mail.163.com/faqDetail.do?code=d7a5dc8471cd0c0e8b4b8f4f8e49998b374173cfe9171305fa1ce630d7f67ac211b1978002df8b23).

> 请您联系软件开发人员更新相关源代码，在连接服务器时带上IMAP ID信息，相关JAVA示例代码如下：（其他语言或框架请联系对应开发者处理，网易仅提供JAVA语言示例代码。）

(Please contact the developer to add IMAP ID when connecting.)

> e.g.

> ```java
> Properties props = new Properties(); 
> props.setProperty("mail.store.protocol", "imap"); 
> props.setProperty("mail.imap.host", "imap.163.com"); 
> props.setProperty("mail.imap.port", "143"); 
> 
> HashMap IAM = new HashMap();
> //带上IMAP ID信息，由key和value组成，例如name，version，vendor，support-email等。
> IAM.put("name","myname");      
> IAM.put("version","1.0.0");      
> IAM.put("vendor","myclient");      
> IAM.put("support-email","testmail@test.com");  
> Session session = Session.getInstance(props); 
> 
> IMAPStore store = (IMAPStore) session.getStore("imap");
> //下方替换对应帐号和授权码
> store.connect("testmail@163.com", "password"); 
> 
> store.id(IAM);
> ```

**Comment by r10s** [comment]
closed by https://github.com/deltachat/provider-db/pull/187, thanks a lot!

nb, for hanging out, you are always welcome to irc/libera #deltachat and other channels!

**Comment by Micraow** [comment]
I still want to use 163 mail. 163 mailbox, the most popular mailbox in China, has the widest user group (many people even think of 163 mailbox when they think of mailbox), and it is very fast.however, Delta Chat doesn't support it. The reason is that it needs an "IMAP ID". I don't think it seems to be a very troublesome thing. Can the developers of delta chat make efforts to make 163 mail available?

**Comment by r10s** [comment]
do you know some english documentation that explains the "IMAP ID" and how that can be retrieved? seems to be a client ID that one has to get from 163.com somehow? if there are further information, also please open a new issue as this one is about QQ mail.

**Comment by Micraow** [comment]
> do you know some english documentation that explains the "IMAP ID" and how that can be retrieved? seems to be a client ID that one has to get from 163.com somehow? if there are further information, also please open a new issue as this one is about QQ mail.
> 
> EDIT: i just noticed there is a new issue at #236 , thanks a lot, @Micraow

I think we don't have to get one from 163.com.

I found some documentation. Hope these can help:

https://javaee.github.io/javamail/docs/api/index.html?com/sun/mail/imap/IMAPStore.html

https://www.ietf.org/rfc/rfc2971.txt

Since I am not a professional programmer, I am sorry that I may not be able to help，but I  will try my best.

**Comment by Micraow** [comment]
Hello, Is there any progress?

**Comment by r10s** [comment]
afaik, no one is working on this issue currently, but at least some ppl agreed internally that supporting QQ Mail as a big provider makes sense :)

i reopen this issue to not be forgotten :)

**Comment by missytake** [comment]
I'm closing this issue again - QQ Mail is supported now. Let's continue this discussion in #236 :)
