### ISSUE TITLE
Use provider page as Howto for manual tasks

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/provider-db#2]
~~- [x] styling~~
~~- [ ] tooltips for properties~~
~~- [x] Edit Link (link to the sources on github)~~

**Comment by pabzm** [comment]
I'd like to highjack this issue, because we have slightly changed plans for each provider' page: they shall serve as HowTo-pages to help new users to configure their provider-accounts, if necessary. The page will be linked from the apps at (or just after) logging in for the first time, if manual tasks are required.

If there's nothing to do for using the respective provider, the page should tell just that, in a friendly manner. It will not be linked from the apps, anyway, but people still might find a link to it somehow, or the provider used to require manual tasks and later doesn't anymore.

The tone of the pages should be friendly and helpful, guiding people that need assistance from their perspective, possibly including screenshots.

The structured data (front matter) of each page should not be visible on this page. We use that data in other contexts (see #44, #42).

**Comment by r10s** [comment]
i'd like to point out, that the goal for now is _not_ to have a "nice webpage" for every provider. steps of details:

1. for most providers, the information from the frontmatter will be sufficient, not even explaining text in the frontmatter will be needed (eg. nauta)

2. if this is not sufficient, the first attempt is to place some freetext in the frontmatter that is displayed in the app then.

3. _only_, if things are so complicated that a separate webpage is needed, the "webpage" should be taken care of. we need an explicit switch "show-url" in the frontmatter in this case to make this explicit. there is no need to bother users with links to webpages that contain things that are not required to login.

i expect 3. to become important only for very few providers (eg. if we want to include the [tb database](https://github.com/deltachat/provider-db/issues/33), everything is just step 1.

**Comment by pabzm** [comment]
See #52 for a beginning

**Comment by r10s** [comment]
i think we sorted that out, however, this is sth. that should be explained in the README, #58
