### ISSUE TITLE
The Fastmail provider document is missing the "Technical Specs" link for custom domains

### ISSUE THREAD

**Issue by sbutler-gh** [deltachat/provider-db#204]
Here is the provider document for Fastmail <> Delta Chat:

https://github.com/deltachat/provider-db/blob/master/_providers/fastmail.md

At the bottom of that page, for custom domains (email addresses served by Fastmail which don't end in `@fastmail.com`), it says:

> If your login email does not end with @fastmail.com, you will need to manually type server information by clicking "Advanced" in Delta Chat and entering the details specified in the "Technical specs" link below

There is no link or further information provided from there, for setting up Delta Chat with Fastmail custom domains.

**Comment by sbutler-gh** [comment]
From investigating further, I see that this markdown was for a corresponding page in the Delta Chat documentation, which includes a link back to this markdown page:

https://providers.delta.chat/fastmail

^ So if a user views this URL, and then clicks the Technical Specs link to the githbub `fastmail.md` page, the table will be understood as the "technical specs" that they should include.

However, if a user first discovers the github `fastmail.md`, it won't necessarily be clear that the technical information they're looking for is in the above table on that same page.  Not sure the best way to communicate that?

**Comment by r10s** [comment]
> However, if a user first discovers the github fastmail.md

github/provider-db is the "source code" for the providers.delta.chat and, most importantly, for the app.

so, if in doubt, it is better that the texts are optimized for the end user looking at https://providers.delta.chat/fastmail and _not_ for
https://raw.githubusercontent.com/deltachat/provider-db/master/_providers/fastmail.md

in case of fastmail, however, it might be even better to just duplicate the settings directly, if custom domains are really a thing and we assume people will find that page in this case (delta chat itself cannot link to the page from the app for custom domains as it currently just not knows about the custom domain - otherwise it would just use the stettings)
