### ISSUE TITLE
IDEA: Query Thunderbirds database

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/provider-db#33]
Pull in data like 
- imap/smtp address, port, authentication, Transport encryption
- domains

https://autoconfig.thunderbird.net/v1.1/{domainname}

**Comment by Simon-Laux** [comment]
First we should think about what information we need and how we want to store it.
thunderbirds config does sometimes provide multiple methods for imap (like with and without ssl)
- how should we represent that in our data structure? use only the encrypted one? store an array? but the latter one would increase the complexity of accessors functions.

**Comment by lefherz** [comment]
could storing only the encrypted connection cause problems with outdated operating systems, which don't support modern TLS? With some old Android 4 I couldn't use Wire, for example. And would those old OSes work with Delta anyway?

**Comment by hpk42** [comment]
On Mon, Oct 14, 2019 at 05:44 -0700, Emil Lefherz wrote:
> could storing only the encrypted connection cause problems with outdated operating systems, which don't support modern TLS? With some old Android 4 I couldn't use Wire, for example. And would those old OSes work with Delta anyway?

i think if the DB says TLS for a domain works but the implementation/os does not support it 
then we can still try other connections (clear etc) or ask the user.

**Comment by missytake** [comment]
The database can be downloaded with this bash command: 

```
curl https://autoconfig.thunderbird.net/v1.1/ | grep -oP 'href="\K.+?"' | sed 's/"//' | awk '{ system("wget https://autoconfig.thunderbird.net/v1.1/"$1) }'
```

it's about 7 MB large.

**Comment by missytake** [comment]
@Simon-Laux and me are in a call right now. We had the idea to create a repository where we extract the information https://github.com/deltachat/deltachat-core-rust/blob/master/src/configure/mod.rs needs from the thunderbird autoconfig database. We would extract it to our own rust structs that get serialized to yaml, so that we can estimate the required space. Then we could use this instead of the network request to thunderbird. later we can include it in the provider db.

We would write a rust script which would do something like this:

1. download the TB db
2. loop over all files in that dir, read into rust struct, then serialize it and save the resulting yml files in a new dir.

This directory could be included into the app.

**Comment by EchedeyLR** [comment]
> could storing only the encrypted connection cause problems with outdated operating systems, which don't support modern TLS? With some old Android 4 I couldn't use Wire, for example. And would those old OSes work with Delta anyway?

Sounds like the reason in which Fedilab allow you to patch security providers in old devices in order to connect to any activitypub-based instance.

**Comment by r10s** [comment]
i think this is nothing we will target in the next weeks.

maybe it is not needed at all - the current idea is to check the local provider-db at first anyway - so, might be that this already speeds up a lot of things significantly and the thunderbird-db is not needed that often.

but we can revisit this if we have some experience with the first versions of shipped provider-db :)
