### ISSUE TITLE
mention nauta.cu mega bots

### ISSUE THREAD

**Issue by missytake** [deltachat/provider-db#79]
In the nauta.cu after_login_hint, it is mentioned that nauta.cu only supports up to 20 recipients. We should also mention the bots which provide a workaround.

**Comment by adbenitez** [comment]
the bot for mega-groups is adb_bot1@testrun.org not sure if it worth to mention it, since the UX of the bots in Delta Chat isn't that good yet, we don't have impersonation, command completion or special bot buttons and we don't have a way to distribute the email to several users at the same time with a BCC, the bot have to send the message to each user one by one which gives delays the more members have the group

**Comment by adbenitez** [comment]
also simplebot is a WIP :)

**Comment by adbenitez** [comment]
well, to use the bot:
- to see public rooms:
/group/list
- to join one room:
/group/join ROOM_URL
- to upgrade a normal group to mega group, just add the bot to the group and send:
/group/mega
- to see/change the topic of the group:
/group/topic
- to see the member lists:
/group/members

**Comment by Simon-Laux** [comment]
I wouldn't mention the bot address, rather hint to the existence of such bots.
Maybe we could also link to an article on your blog @adbenitez

**Comment by pabzm** [comment]
Please do not mention the bots in the login-hints. Bots are still rather rough, not yet suitable for the general, less-involved public.

The login-hints are for short, necessary information for each and every person out there. They must be easily understandable, and avoid specialized or technical details.

Bots are (for now) a topic for a small group of (socially) involved or tech-savvy people. I consider the forum an appropriate place for that kind of topic.

**Comment by missytake** [comment]
Okay, then let's close this for now :)
